# Generated by Django 5.0.4 on 2024-04-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_localbody'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_localbody',
        ),
        migrations.DeleteModel(
            name='tbl_localbodytype',
        ),
    ]
