# Generated by Django 5.0.4 on 2024-04-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_donationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('member_count', models.CharField(max_length=50)),
            ],
        ),
    ]
