# Generated by Django 5.0.4 on 2024-04-27 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_teammember',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_team'),
        ),
    ]
