# Generated by Django 5.0.4 on 2024-04-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_remove_tbl_teammember_team_tbl_teammember_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_teammember',
            name='member_proof',
            field=models.FileField(upload_to='Memberproof/'),
        ),
    ]
