# Generated by Django 5.0.4 on 2024-04-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_tbl_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_name', models.CharField(max_length=50)),
                ('registration_contact', models.CharField(max_length=50)),
                ('registration_email', models.CharField(max_length=50)),
                ('registration_password', models.CharField(max_length=50)),
            ],
        ),
    ]
