# Generated by Django 5.0.4 on 2024-04-29 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_tbl_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_teammember',
            name='assignment',
        ),
    ]
