# Generated by Django 5.0.4 on 2024-04-29 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_remove_tbl_teammember_assignment'),
        ('Teammember', '0010_alter_tbl_family_teammember_alter_tbl_product_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_teammember',
        ),
    ]
