# Generated by Django 5.0.4 on 2024-04-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_tbl_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_teammember',
            name='member_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
