# Generated by Django 5.0.4 on 2024-04-27 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0009_alter_tbl_teammember_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_housename', models.CharField(max_length=50)),
                ('family_address', models.CharField(max_length=50)),
                ('teammember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_teammember')),
            ],
        ),
    ]
