# Generated by Django 5.0.4 on 2024-04-27 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teammember', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_familymember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_member_counter', models.CharField(max_length=50)),
                ('family_member_name', models.CharField(max_length=50)),
                ('family_member_gender', models.CharField(max_length=50)),
                ('family_member_age', models.CharField(max_length=50)),
                ('family_member_relation', models.CharField(max_length=50)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teammember.tbl_family')),
            ],
        ),
    ]
