# Generated by Django 5.0.4 on 2024-04-27 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teammember', '0003_tbl_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_product',
        ),
    ]
