# Generated by Django 5.0.4 on 2024-04-27 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teammember', '0005_tbl_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Teammember.tbl_family'),
        ),
    ]
