# Generated by Django 5.0.4 on 2024-04-27 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_tbl_registration'),
        ('Teammember', '0007_tbl_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_familyneedlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need', models.CharField(max_length=50)),
                ('donationtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_donationtype')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teammember.tbl_family')),
            ],
        ),
    ]
