# Generated by Django 5.0.4 on 2024-04-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teammember', '0008_tbl_familyneedlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_familyneedlist',
            name='need_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
