# Generated by Django 5.0.4 on 2024-04-29 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_teammember'),
        ('Teammember', '0009_tbl_familyneedlist_need_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_family',
            name='teammember',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_teammember'),
        ),
        migrations.AlterField(
            model_name='tbl_product',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_teammember'),
        ),
    ]
