# Generated by Django 5.0.4 on 2024-04-29 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_tbl_teammember'),
        ('Teammember', '0010_alter_tbl_family_teammember_alter_tbl_product_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_family',
            name='teammember',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_teammember'),
        ),
        migrations.AlterField(
            model_name='tbl_product',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_teammember'),
        ),
    ]
