# Generated by Django 5.0.4 on 2024-04-29 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teammember', '0012_remove_tbl_familymember_family_member_counter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_product',
            name='product_stock',
        ),
    ]
