# Generated by Django 5.0.4 on 2024-04-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_userreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userregistration_name', models.CharField(max_length=50)),
                ('userregistration_contact', models.CharField(max_length=50)),
                ('userregistration_email', models.CharField(max_length=50)),
                ('userregistration_address', models.CharField(max_length=50)),
                ('userregistration_photo', models.FileField(upload_to='UserDoc/')),
                ('userregistration_proof', models.FileField(upload_to='UserDoc/')),
                ('userregistration_password', models.CharField(max_length=50)),
            ],
        ),
    ]
