# Generated by Django 5.0.4 on 2024-04-29 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_teammember'),
        ('Teammember', '0011_alter_tbl_family_teammember_alter_tbl_product_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_teammember',
        ),
    ]
