# Generated by Django 5.0.4 on 2024-04-27 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_tbl_registration'),
        ('Guest', '0001_initial'),
        ('Teammember', '0008_tbl_familyneedlist'),
        ('User', '0004_tbl_complaint_tbl_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField(auto_now_add=True)),
                ('donation_amount', models.CharField(max_length=50)),
                ('donation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_donationtype')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teammember.tbl_family')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userreg')),
            ],
        ),
    ]
