# Generated by Django 5.0.4 on 2024-04-29 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teammember', '0009_tbl_familyneedlist_need_status'),
        ('User', '0005_tbl_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_donation',
            name='family',
        ),
        migrations.AddField(
            model_name='tbl_donation',
            name='family_need',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Teammember.tbl_familyneedlist'),
        ),
    ]
