# Generated by Django 5.0.4 on 2024-04-29 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_remove_tbl_donation_family_tbl_donation_family_need'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_donation',
            name='donation_type',
        ),
    ]
