# Generated by Django 5.0.4 on 2024-04-29 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_tbl_registration'),
        ('User', '0007_remove_tbl_donation_donation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_donation',
            name='family_need',
        ),
        migrations.AddField(
            model_name='tbl_donation',
            name='donation_details',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbl_donation',
            name='donation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_donationtype'),
        ),
    ]
