# Generated by Django 5.0.4 on 2024-04-29 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_remove_tbl_donation_family_need_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_donation',
            name='donation_amount',
        ),
    ]
